/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midterm;

import java.util.Scanner;
import java.util.Random;

/**
 *
 * @author Dora72
 */
public class Midterm {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String personPlay;
        String computerPlay;
        String exit = null;
        float win = 0;
        float loss = 0;
        float gamesPlayed = 0;
        float even = 0; //Guessed by player
        float odd = 0; //Generated by dice
        int computerInt; //Randomly generated number
        float winPercent;
        float evenPercent;
        float oddPercent;
        Scanner scan = new Scanner(System.in);
        Random generator = new Random();
        while (!"x".equals(exit)) {
            computerInt = generator.nextInt(6) + 1;
            if (computerInt == 2 || computerInt == 4 || computerInt == 6) {
                computerPlay = "e";
            } else {
                computerPlay = "o";
                odd++;
            }
            System.out.println("Guess odd (o) or even (e): ");
            personPlay = scan.next();
            if (personPlay.equals("e")) {
                even++;
            }
            if (computerPlay.equals(personPlay)) {
                System.out.println("You win!!!");
                win++;
            } else {
                System.out.println("You lose!!!");
                loss++;
            }
            System.out.println("The die rolled " + computerInt + ".");
            gamesPlayed++;
            System.out.println("You have played " + gamesPlayed + " games.");
            winPercent = win / gamesPlayed * 100;
            System.out.println("Your winning percentage is " + winPercent + "%.");
            evenPercent = even / gamesPlayed * 100;
            System.out.println("You guessed even " + evenPercent + "% of the games.");
            oddPercent = odd / gamesPlayed * 100;
            System.out.println("The CPU chose odd " + oddPercent + "% of the games.");
            System.out.println("Type x to exit or any other key and Enter to keep playing.");
            exit = scan.next();
        }
    }
}
